repos:
  - repo: https://github.com/python/black.git
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3.7
  - repo: https://gitlab.com/pycqa/flake8.git
    rev: 3.8.4
    hooks:
      - id: flake8
        language_version: python3.7
