{{- if .Values.database.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "liquidity.fullname" . }}-db
  labels:
    app: {{ include "liquidity.fullname" . }}-db
    {{- include "liquidity.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "liquidity.fullname" . }}-db
    {{- include "liquidity.selectorLabels" . | nindent 4 }}
  ports:
  - protocol: "TCP"
    port: {{ .Values.database.port }}
    targetPort: {{ .Values.database.port }}
    name: db
{{- end }}
